server:
  port: 8080

mqtt:
  host: mosquitto
  subTopic: moisture
  pubTopic: water

spring:
  data:
    mongodb:
      database: mqtt_data
      username: root
      password: root
      port: 27017
      host: mqtt-mongo-db