server:
  port: 8080

mqtt:
  #host: mosquitto
  host: test.mosquitto.org
  subTopic: S2110454011/moisture
  pubTopic: S2110454011/water

spring:
  data:
    mongodb:
      database: mqtt_data
      username: root
      password: root
      port: 27017
      host: mqtt-mongo-db